// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4579.Lancelot.subsystems;

import org.usfirst.frc4579.Lancelot.RobotMap;
import org.usfirst.frc4579.Lancelot.commands.*;

import com.RoboEagles4579.filters.SecondOrderLPF;

import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drivetrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController leftMotor = RobotMap.drivetrainleftMotor;
    private final SpeedController rightMotor = RobotMap.drivetrainrightMotor;
    private final RobotDrive robotDrive = RobotMap.drivetrainrobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    private final SecondOrderLPF xLPF = new SecondOrderLPF();
    private final SecondOrderLPF yLPF = new SecondOrderLPF();
    private boolean reversedDrive = false;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    
    public void drive(double x, double y) {
 
    	x = xLPF.filter(x);
    	y = yLPF.filter(y);
    	
    	x = reversedDrive ? -x : x;
    	y = reversedDrive ? -y : y;
    	    	
    	robotDrive.arcadeDrive(x, y);
    	
    }
    
    public void reverseDrive() {
    	reversedDrive = !reversedDrive;
    }
    
    public void stop() {
    	leftMotor.set(0);
    	rightMotor.set(0);
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new Cmd_Default_Drive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

